# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Quantum Meditations' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for Quantum Meditations
  pod 'Parse'

  pod "AlamofireImage"
  pod 'MessageInputBar'

end
